client_config_backend: settings
client_config:
  client_id: 863742201507-3ofoc79ja1v7a5ctc2qrgs7j3kk15seu.apps.googleusercontent.com
  client_secret: JUYnRNj6yJm9WvKHWGek-Cue

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install